// Generates shared/src/abis.ts from Foundry build output, so TypeScript ABIs always match the contracts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const contracts = {
  sealedOrderAdapterAbi: "SealedOrderAdapter.sol/SealedOrderAdapter.json",
  userAccountAbi: "UserAccount.sol/UserAccount.json",
  chainlinkFeedPriceVerifierAbi: "ChainlinkFeedPriceVerifier.sol/ChainlinkFeedPriceVerifier.json",
  aggregatorV3Abi: "IAggregatorV3.sol/IAggregatorV3.json",
};

let out = "// Generated by shared/scripts/gen-abis.mjs from contracts/out. Do not edit; run `pnpm abis`.\n\n";
for (const [name, file] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(join(root, "contracts", "out", file), "utf8"));
  out += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "shared", "src", "abis.ts"), out);
console.log("wrote shared/src/abis.ts");
