// Generates shared/src/abis.ts from Foundry build output, so TypeScript ABIs always match the contracts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const contracts = {
  sealedOrderAdapterAbi: "SealedOrderAdapter.sol/SealedOrderAdapter.json",
  userAccountAbi: "UserAccount.sol/UserAccount.json",
  chainlinkFeedPriceVerifierAbi: "ChainlinkFeedPriceVerifier.sol/ChainlinkFeedPriceVerifier.json",
  aggregatorV3Abi: "IAggregatorV3.sol/IAggregatorV3.json",
};

let out = "// Generated by shared/scripts/gen-abis.mjs from contracts/out. Do not edit; run `pnpm abis`.\n\n";
for (const [name, file] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(join(root, "contracts", "out", file), "utf8"));
  out += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "shared", "src", "abis.ts"), out);
console.log("wrote shared/src/abis.ts");

// L2 block of the latest deployment, for log scans (on Arbitrum, block.number in contracts is the L1 block).
import { existsSync } from "node:fs";
const broadcast = join(root, "contracts", "broadcast", "Deploy.s.sol", "421614", "run-latest.json");
let block = 0n;
if (existsSync(broadcast)) {
  const blocks = JSON.parse(readFileSync(broadcast, "utf8")).receipts.map((r) => BigInt(r.blockNumber));
  if (blocks.length) block = blocks.reduce((a, b) => (a < b ? a : b));
}
writeFileSync(
  join(root, "shared", "src", "deployment.ts"),
  "// Generated by shared/scripts/gen-abis.mjs from contracts/broadcast. Do not edit; run `pnpm abis` after deploying.\n\n" +
    `/** First L2 block of the latest deployment (0 if unknown). */\nexport const deploymentBlock = ${block}n;\n`,
);
console.log(`wrote shared/src/deployment.ts (deploymentBlock ${block})`);
