[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
auto_detect_remappings = false
ignored_warnings_from = ["node_modules"]
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "hardhat/=node_modules/forge-std/src/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@fhenixprotocol/cofhe-contracts/=node_modules/@fhenixprotocol/cofhe-contracts/",
  "@cofhe/mock-contracts/=node_modules/@cofhe/mock-contracts/",
  "@cofhe/foundry-plugin/=node_modules/@cofhe/foundry-plugin/contracts/",
]
fs_permissions = [{ access = "read", path = "../config" }, { access = "read-write", path = "../deployments" }]

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[lint]
lint_on_build = false
