// Generated by shared/scripts/gen-abis.mjs from contracts/broadcast. Do not edit; run `pnpm abis` after deploying.

/** First L2 block of the latest deployment (0 if unknown). */
export const deploymentBlock = 315241402n;
